Feature/#445
ATLauncher/ATLauncher pull request #528
Opened 2021-12-02 13:23 UTC by s0cks

### Description of the Change

This should allow sorting of instances by with a variety of different sorting strategies

### Testing

Lightly tested locally. No unit tests, will add if wanted.

### Related Issues

Fixes: #445

2021-12-03 00:01 UTC, RyanTheAllmighty requested changes
Thanks for this. And welcome back, hope all has been well.

Looks like builds failing due to missing license headers, just run `./gradlew updateLicenses` to update them and commit them back up.

2021-12-03 18:13 UTC, s0cks commented on src/main/java/com/atlauncher/Gsons.java
> +import com.atlauncher.data.*;
Sure thing, I just installed Idea on this laptop so still sorting out the little things
~ Tazz

2021-12-03 18:14 UTC, s0cks commented on src/main/java/com/atlauncher/gui/components/CollapsiblePanel.java
> +        final DateTimeFormatter formatter = DateTimeFormatter.ofLocalizedDateTime(FormatStyle.SHORT)
Honestly this wasnt supposed to make it in the PR, but if you'd like to change the title sure thing. 

I was using it to test the sorting.
~ Tazz

2021-12-03 18:18 UTC, s0cks commented on src/main/java/com/atlauncher/gui/tabs/InstancesTab.java
> +    public void itemStateChanged(ItemEvent e){
- Less generated/anonymous classes
- Somewhat cleaner 
while still providing access to the instance variables
~ Tazz

2021-12-03 18:20 UTC, s0cks commented
> Thanks for this. And welcome back, hope all has been well.
> 
> Looks like builds failing due to missing license headers, just run `./gradlew updateLicenses` to update them and commit them back up.

Sure thing, thanks!

Was looking for something to code-related to work on in some new found spare time!

I'll take a look at cleaning this up tonight

2021-12-04 00:53 UTC, RyanTheAllmighty commented on src/main/java/com/atlauncher/gui/components/CollapsiblePanel.java
> +        final DateTimeFormatter formatter = DateTimeFormatter.ofLocalizedDateTime(FormatStyle.SHORT)
I don't mind. If it was just something for testing then can just remove it. Play time likely isn't something many people want to see anyway I'd imagine

2021-12-30 03:47 UTC, RyanTheAllmighty approved these changes

2021-12-30 03:47 UTC, RyanTheAllmighty commented
Thanks for this, and sorry for the delay in getting this merged. But looks good to me

2021-12-30 03:47 UTC, merged