Added Feature from issue 762
ATLauncher/ATLauncher pull request #803
Opened 2023-08-12 09:26 UTC by Red-S2

### Description of the Change

This pr adds the button requested in issue 762 as well as the reminder not do distribute any resources

### Testing

Tested for multiple modloaders and versions

### Related Issues

https://github.com/ATLauncher/ATLauncher/issues/762

2023-08-12 09:38 UTC, RyanTheAllmighty requested changes

2023-08-12 09:38 UTC, RyanTheAllmighty commented on src/main/java/com/atlauncher/gui/card/InstanceCard.java
> +    private final JButton openResourceButton = new JButton(GetText.tr("Open Resources"));
The bottom row of buttons I don't think can show any more at the default size.

Can you copy what was done for the Play buttons where it's a dropdownbutton with the default action being Open Folder and then have this new one in the drop-down like play offline button is

2023-08-12 09:38 UTC, RyanTheAllmighty commented on src/main/java/com/atlauncher/gui/card/InstanceCard.java
> +            DialogManager.okDialog().setTitle("Reminder")
Any text should be wrapped in `GetText.tr()`

2023-08-12 09:38 UTC, RyanTheAllmighty commented on src/main/java/com/atlauncher/gui/card/InstanceCard.java
> +                    .setContent("You may not distribute ANY resources.")
Same here for `GetText.tr()`

2023-08-12 09:38 UTC, RyanTheAllmighty commented on src/main/java/com/atlauncher/gui/card/InstanceCard.java
> +                    .setType(DialogManager.OK_OPTION).show();
This should probably be the `WARNING` constant from DialogManager

2023-08-15 05:58 UTC, Red-S2 commented
pls review

2023-08-17 00:15 UTC, RyanTheAllmighty requested changes

2023-08-17 14:22 UTC, Red-S2 commented on src/main/java/com/atlauncher/gui/card/InstanceCard.java
> +    private final DropDownButton openButton = new DropDownButton(GetText.tr("Open Files"), openPopupMenu, true,
Done

2023-08-18 06:16 UTC, merged