Update README.md
ATLauncher/ATLauncher pull request #827
Opened 2023-10-08 12:04 UTC by Indominous

fixed a few spelling mistakes, made it clearer

2023-10-08 13:00 UTC, RyanTheAllmighty commented on README.md
> -    brand colours and some defaults. This shouldn't be extended from unless you need absolute power.
This is not incorrect, launchers base language including all documentation is en-gb not en-us

2023-10-08 13:01 UTC, RyanTheAllmighty requested changes
One change and a change log entry must be added for any PR to be merged

2023-10-23 23:15 UTC, some-du6e commented
["Running In Test"](https://github.com/ATLauncher/ATLauncher#running-in-test) really?

2023-11-08 08:11 UTC, closed without merging

2023-11-08 08:11 UTC, RyanTheAllmighty commented
Closing due to inactivity