Update README.md to fix typos
ATLauncher/ATLauncher pull request #899
Opened 2024-05-15 19:04 UTC by ellet0

### Description of the Change

Most of the typo fixes are automated using the IDE, this change doesn't need to be documented as it doesn't affect the application in any way.

2024-05-17 10:33 UTC, RyanTheAllmighty requested changes

2024-05-17 10:33 UTC, RyanTheAllmighty commented on README.md
> +Stream is used to defining if it's a "Release" or a "Beta". When not provided, it defaults to "Release".
This is incorrect

2024-05-17 10:33 UTC, RyanTheAllmighty commented on README.md
> +This will build the application and output the resulting files for Windows, Linux, and OSX in the `dist` directory.
Comma here is unnecessary, don't put a comma before and in a list - https://www.grammarly.com/blog/comma-before-and/#:~:text=Comma%20before%20and%20in%20lists

2024-05-17 10:33 UTC, RyanTheAllmighty commented on README.md
> +ATLauncher is a launcher for Minecraft which integrates multiple different mod-packs to allow you to download and install
modpacks is already correct here. There is no dash in any platform that uses the word, so modpacks is what I've used to keep in line with every other platform

2024-05-17 23:47 UTC, RyanTheAllmighty approved these changes
Approving, but still needs a CHANGELOG.md entry added (Under misc section please)

2024-05-18 12:21 UTC, ellet0 commented
> Approving, but still needs a CHANGELOG.md entry added (Under misc section please)

Thank you for your feedback, I understand the importance of maintaining high standards on this project

I will do my best to ensure send High-quality issue reports and PRs that are made with more effort next time.

Closing this issue, for more details feel free to DM me on Discord

Thank you once again for your understanding.

2024-05-18 12:21 UTC, closed without merging