feat: Add version option for CLI
ATLauncher/ATLauncher pull request #915
Opened 2024-06-05 21:51 UTC by Doomsdayrs

### Description of the Change

Add version option for CLI.

### Testing

- [x] Execute jar normally
- [x] Execute jar with: `-v`, `--v`,  `--version` 

### Related Issues

Closes #914

2024-07-22 12:43 UTC, RyanTheAllmighty requested changes

2024-07-22 12:43 UTC, RyanTheAllmighty commented on src/main/java/com/atlauncher/App.java
> +            System.out.println(Constants.VERSION);
Can you change this to print out `System.out.println(String.format("%s %s", Constants.LAUNCHER_NAME, Constants.VERSION.toStringForLogging()));`

2024-07-25 12:02 UTC, RyanTheAllmighty approved these changes

2024-07-25 12:03 UTC, merged

2025-01-25 05:22 UTC, GetPsyched commented
Thanks!